#!/bin/sh
#
# Copyright (C) 2018 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

if [ -e /proc/device-tree/chosen/default-hostname ]; then
	ucidef_set_hostname `cat /proc/device-tree/chosen/default-hostname`
else
	ucidef_set_hostname "iStoreOS"
fi

ucidef_set_ntpserver "0.cn.pool.ntp.org" "1.cn.pool.ntp.org" "2.cn.pool.ntp.org" "3.cn.pool.ntp.org"

board_config_flush

exit 0